[tool.poetry]
name = "hands-and-objects"
version = "0.1.0"
description = ""
authors = ["pasca-l <shion.yamadate@keio.jp>"]
readme = "README.md"
packages = [{include = "hands_and_objects"}]

[tool.poetry.dependencies]
python = "^3.10"
pytorch-lightning = "^1.9.1"
opencv-python = "^4.7.0.68"
torchvision = "^0.14.1"
segmentation-models-pytorch = "^0.3.2"
gitpython = "^3.1.31"
jupyter = "^1.0.0"
pandas = "^1.5.3"
matplotlib = "^3.7.0"
tensorboard = "^2.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
